//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRecords
    {
        public int GRID { get; set; }
        public int Gid { get; set; }
        public int Team1 { get; set; }
        public int Team2 { get; set; }
        public int WTeam { get; set; }
        public int Sepectators { get; set; }
        public int TotalScore { get; set; }
        public int T1WinScore { get; set; }
        public int T1LoseScore { get; set; }
        public int T2WinScore { get; set; }
        public int T2LoseScore { get; set; }
        public System.DateTime Date { get; set; }
        public int Week { get; set; }
    
        public virtual Games Game { get; set; }
        public virtual Teams Team { get; set; }
        public virtual Teams Team3 { get; set; }
    }
}
